### PR TITLE
Remove element matcher, replace with pattern match

### LINKED ISSUE #1027: App fails to start with java.lang.NoClassDefFoundError on 2.19
After uprgading `kamon-bundle` to 2.19 with kanela-agent 1.0.9, application instantly fails after `Kamon.init()` call with the following error:

```
[main] ERROR 2021-05-27 22:57:17  Logger : Unable to start Kanela Agent.
Please remove -javaagent from your startup arguments and contact Kanela support.: java.lang.NoClassDefFoundError: redis/clients/jedis/commands/ProtocolCommand
	at kamon.instrumentation.jedis.JedisInstrumentation.<init>(JedisInstrumentation.scala:11)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at kanela.agent.InstrumentationLoader.lambda$loadInstrumentation$b85f757d$1(InstrumentationLoader.java:58)
	at kanela.agent.libs.io.vavr.control.Try.of(Try.java:75)
	at kanela.agent.InstrumentationLoader.loadInstrumentation(InstrumentationLoader.java:56)
	at kanela.agent.InstrumentationLoader.lambda$null$1(InstrumentationLoader.java:46)
	at kanela.agent.libs.io.vavr.collection.List.flatMap(List.java:902)
	at kanela.agent.InstrumentationLoader.lambda$load$4(InstrumentationLoader.java:46)
	at kanela.agent.libs.io.vavr.collection.List.map(List.java:1042)
	at kanela.agent.InstrumentationLoader.load(InstrumentationLoader.java:43)
	at kanela.agent.Kanela.lambda$null$0(Kanela.java:79)
	at kanela.agent.util.classloader.InstrumentationClassPath.use(InstrumentationClassPath.java:84)
	at kanela.agent.Kanela.lambda$start$1(Kanela.java:68)
	at kanela.agent.util.Execution.timed(Execution.java:32)
	at kanela.agent.util.Execution.runWithTimeSpent(Execution.java:41)
	at kanela.agent.Kanela.start(Kanela.java:67)
	at kanela.agent.Kanela.premain(Kanela.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)

```

The only thing that allows application to start correctly is disabling redis instrumentation explicitly via
```
kanela.modules.redis.instrumentations = []
```

### PR DESCRIPTION
**Pull request by SimunKaracic**
Fix #1027

### CODE REVIEW

File: instrumentation/kamon-redis/src/main/scala/kamon/instrumentation/jedis/JedisInstrumentation.scala [hunk 1]
```diff
@@ -8,27 +8,29 @@ import redis.clients.jedis.commands.ProtocolCommand
...
-
 object SendCommandAdvice {
   @Advice.OnMethodEnter()
-  def enter(@Advice.Argument(1) command: ProtocolCommand) = {
-    val spanName = s"redis.command.${command}"
-    val span = Kamon.clientSpanBuilder(spanName, "redis.client.jedis")
-      .start()
-
-    span
+  def enter(@Advice.Argument(1) command: Any) = {
```
Comment (ivantopo) [inline instrumentation/kamon-redis/src/main/scala/kamon/instrumentation/jedis/JedisInstrumentation.scala:17]: I'm not 100% sure that mentions of the `ProtocolCommand` type must be removed from here. Have you tried keepting this method the same as it was before?

Comment (SimunKaracic) [reply instrumentation/kamon-redis/src/main/scala/kamon/instrumentation/jedis/JedisInstrumentation.scala:17]: It's there cause there's two methods called sendCommand with 3 arguments. If I leave it as ProtocolCommand, this advice will try to instrument both methods, and fail when the second argument isn't a protocol command
image

Comment (SimunKaracic) [reply instrumentation/kamon-redis/src/main/scala/kamon/instrumentation/jedis/JedisInstrumentation.scala:17]: I'll revert the advice to test whether it fails

Comment (SimunKaracic) [reply instrumentation/kamon-redis/src/main/scala/kamon/instrumentation/jedis/JedisInstrumentation.scala:17]: It fails if I leave ProtocolCommand in the signature: 
```
ERROR 2021-05-28 11:20:41  Logger : Error => redis.clients.jedis.Protocol with message 
Cannot assign [B arg1 to interface redis.clients.jedis.commands.ProtocolCommand. 
Class loader: sun.misc.Launcher$AppClassLoader@18b4aac2: 
java.lang.IllegalStateException: Cannot assign [B arg1 to interface redis.clients.jedis.commands.ProtocolCommand
```

Comment (ivantopo) [reply instrumentation/kamon-redis/src/main/scala/kamon/instrumentation/jedis/JedisInstrumentation.scala:17]: Got it, then it goes in as `Any` :muscle:

File: instrumentation/kamon-redis/src/main/scala/kamon/instrumentation/jedis/JedisInstrumentation.scala [hunk 2]
```diff
@@ -8,27 +8,29 @@ import redis.clients.jedis.commands.ProtocolCommand
...
+    command match {
+      case command: ProtocolCommand =>
+        val spanName = s"redis.command.${command}"
+        Some(Kamon.clientSpanBuilder(spanName, "redis.client.jedis")
+          .start())
+      case _ => None
```
Comment (ivantopo) [inline instrumentation/kamon-redis/src/main/scala/kamon/instrumentation/jedis/JedisInstrumentation.scala:23]: Tiny thing: you could use `Span.Empty` to avoid creating options altogether, specially because you know that 100% of the time the argument will be `ProtocolCommand`. If you return `Span` instead of `Option[Span]` the exit would be exactly the same as it was before, and it will do nothing if it ever gets `Span.Empty`
